//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.22 at 03:11:15 AM TRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://tckimlik.nvi.gov.tr/WS", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.argmnt.turkish_identity_checker.identity_domain;
